// apps/kimi-web/src/api/desktop/supportedMethods.ts
// The desktop product transport's supported-method registry — every
// KimiWebApi member WailsKimiWebApi implements (re-exported by client.ts).

/**
 * Every KimiWebApi member `WailsKimiWebApi` implements — the complete desktop
 * product transport surface (all 81 members, kept in sync by the
 * `implements KimiWebApi` clause; `deleteSession` / `setDefaultModel` are
 * class-only leftovers and intentionally absent). The coverage test
 * (`test/product-method-coverage.test.ts`) asserts this list against the
 * sidecar `ProductFacade` dispatch tables so a client method can never target
 * a product method the real shell does not register.
 */
export const DESKTOP_SUPPORTED_METHODS: readonly string[] = [
  'getHealth',
  'getMeta',
  'listSessions',
  'createSession',
  'getSession',
  'updateSession',
  'getSessionStatus',
  'getSessionGoal',
  'getSessionWarnings',
  'archiveSession',
  'restoreSession',
  'listMessages',
  'getSessionSnapshot',
  'exportSession',
  'submitPrompt',
  'steerPrompts',
  'abortPrompt',
  'abortSession',
  'compactSession',
  'undoSession',
  'forkSession',
  'createChildSession',
  'listChildSessions',
  'startBtw',
  'respondApproval',
  'respondQuestion',
  'dismissQuestion',
  'listSkills',
  'listSkillsForWorkspace',
  'activateSkill',
  'listExtensionCommands',
  'reloadExtensions',
  'activateExtensionCommand',
  'listExpertTeams',
  'getExpertTeam',
  'activateExpertTeam',
  'deactivateExpertTeam',
  'listTasks',
  'getTask',
  'cancelTask',
  'listTerminals',
  'createTerminal',
  'getTerminal',
  'closeTerminal',
  'listDirectory',
  'readFile',
  'searchFiles',
  'grepFiles',
  'getGitStatus',
  'getFileDiff',
  'getFileDownloadUrl',
  'getWorkspaceFileBlob',
  'openFile',
  'revealFile',
  'openInApp',
  'connectEvents',
  'listWorkspaces',
  'addWorkspace',
  'updateWorkspace',
  'deleteWorkspace',
  'browseFs',
  'getFsHome',
  'listModels',
  'listProviders',
  'createProvider',
  'getProvider',
  'replaceProvider',
  'deleteProvider',
  'refreshProvider',
  'refreshAllProviders',
  'refreshOAuthProviderModels',
  'uploadFile',
  'getFileUrl',
  'getFileBlob',
  'supportsSyncFileUrls',
  'getConfig',
  'setConfig',
  'getAuth',
  'startOAuthLogin',
  'pollOAuthLogin',
  'cancelOAuthLogin',
  'logout',
];
